var all = [
    {
        "id":1,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"工单管理",
        "guard_name":"api",
        "path":"/tools",
        "path_name":"tools",
        "title":"工单管理",
        "icon":"wrench",
        "redirect":null,
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":1
        }
    },
    {
        "id":2,
        "pid":1,
        "pid_path":"1",
        "menu":1,
        "order":0,
        "name":"预约",
        "guard_name":"api",
        "path":"touch",
        "path_name":"touch",
        "title":"预约",
        "icon":"chatbox-working",
        "redirect":"",
        "component":"tools.touch",
        "pivot":{
            "role_id":1,
            "permission_id":2
        }
    },
    {
        "id":3,
        "pid":1,
        "pid_path":"1",
        "menu":1,
        "order":0,
        "name":"新建工单",
        "guard_name":"api",
        "path":"new-workorder",
        "path_name":"new-workorder",
        "title":"新建工单",
        "icon":"model-s",
        "redirect":null,
        "component":"tools.newWorkorder",
        "pivot":{
            "role_id":1,
            "permission_id":3
        }
    },
    {
        "id":4,
        "pid":1,
        "pid_path":"1",
        "menu":1,
        "order":0,
        "name":"工单",
        "guard_name":"api",
        "path":"workorder",
        "path_name":"workorder",
        "title":"工单",
        "icon":"ios-paper",
        "redirect":"",
        "component":"tools.workorder",
        "pivot":{
            "role_id":1,
            "permission_id":4
        }
    },
    {
        "id":5,
        "pid":1,
        "pid_path":"1",
        "menu":1,
        "order":0,
        "name":"洗车",
        "guard_name":"api",
        "path":"wash",
        "path_name":"wash",
        "title":"洗车",
        "icon":"leaf",
        "redirect":null,
        "component":"tools.wash",
        "pivot":{
            "role_id":1,
            "permission_id":5
        }
    },
    {
        "id":9,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"采购管理",
        "guard_name":"api",
        "path":"/purchase",
        "path_name":"purchase",
        "title":"采购管理",
        "icon":"ios-cart",
        "redirect":null,
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":9
        }
    },
    {
        "id":10,
        "pid":9,
        "pid_path":"9",
        "menu":1,
        "order":3,
        "name":"采购订单",
        "guard_name":"api",
        "path":"purchase-order",
        "path_name":"purchase-order",
        "title":"采购订单",
        "icon":"ios-paper-outline",
        "redirect":null,
        "component":"purchase.order",
        "pivot":{
            "role_id":1,
            "permission_id":10
        }
    },
    {
        "id":13,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"库存管理",
        "guard_name":"api",
        "path":"/inventory",
        "path_name":"inventory",
        "title":"库存管理",
        "icon":"ios-albums",
        "redirect":null,
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":13
        }
    },
    {
        "id":15,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":0,
        "name":"入库单",
        "guard_name":"api",
        "path":"entry",
        "path_name":"entry",
        "title":"入库单",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"inventory.entry",
        "pivot":{
            "role_id":1,
            "permission_id":15
        }
    },
    {
        "id":16,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":0,
        "name":"出库单",
        "guard_name":"api",
        "path":"outbound",
        "path_name":"outbound",
        "title":"出库单",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"inventory.outbound",
        "pivot":{
            "role_id":1,
            "permission_id":16
        }
    },
    {
        "id":19,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":0,
        "name":"库位管理",
        "guard_name":"api",
        "path":"adjustment",
        "path_name":"adjustment",
        "title":"库位管理",
        "icon":"android-navigate",
        "redirect":null,
        "component":"inventory.adjustment",
        "pivot":{
            "role_id":1,
            "permission_id":19
        }
    },
    {
        "id":27,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"数据管理",
        "guard_name":"api",
        "path":"/data",
        "path_name":"data",
        "title":"数据管理",
        "icon":"shuffle",
        "redirect":"",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":27
        }
    },
    {
        "id":28,
        "pid":27,
        "pid_path":"27",
        "menu":1,
        "order":0,
        "name":"车型信息",
        "guard_name":"api",
        "path":"cartype",
        "path_name":"cartype",
        "title":"车型信息",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"dataManager.cartype",
        "pivot":{
            "role_id":1,
            "permission_id":28
        }
    },
    {
        "id":29,
        "pid":27,
        "pid_path":"27",
        "menu":1,
        "order":0,
        "name":"配件信息",
        "guard_name":"api",
        "path":"autoparts",
        "path_name":"autoparts",
        "title":"配件信息",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"dataManager.autoparts",
        "pivot":{
            "role_id":1,
            "permission_id":29
        }
    },
    {
        "id":31,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"报表管理",
        "guard_name":"api",
        "path":"/chart",
        "path_name":"chart",
        "title":"报表管理",
        "icon":"pie-graph",
        "redirect":null,
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":31
        }
    },
    {
        "id":34,
        "pid":31,
        "pid_path":"31",
        "menu":1,
        "order":0,
        "name":"采购报表",
        "guard_name":"api",
        "path":"chart-purchase",
        "path_name":"chart-purchase",
        "title":"采购报表",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"chart.chartPurchase",
        "pivot":{
            "role_id":1,
            "permission_id":34
        }
    },
    {
        "id":35,
        "pid":31,
        "pid_path":"31",
        "menu":1,
        "order":0,
        "name":"客户报表",
        "guard_name":"api",
        "path":"chart-customer",
        "path_name":"chart-customer",
        "title":"客户报表",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"chart.chartCustomer",
        "pivot":{
            "role_id":1,
            "permission_id":35
        }
    },
    {
        "id":36,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"财务管理",
        "guard_name":"api",
        "path":"/finance",
        "path_name":"finance",
        "title":"财务管理",
        "icon":"social-yen",
        "redirect":"",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":36
        }
    },
    {
        "id":38,
        "pid":36,
        "pid_path":"36",
        "menu":1,
        "order":0,
        "name":"应收账款",
        "guard_name":"api",
        "path":"receivable",
        "path_name":"receivable",
        "title":"应收账款",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"finance.receivable",
        "pivot":{
            "role_id":1,
            "permission_id":38
        }
    },
    {
        "id":39,
        "pid":36,
        "pid_path":"36",
        "menu":1,
        "order":0,
        "name":"应付",
        "guard_name":"api",
        "path":"payable",
        "path_name":"payable",
        "title":"应付",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"finance.payable",
        "pivot":{
            "role_id":1,
            "permission_id":39
        }
    },
    {
        "id":40,
        "pid":36,
        "pid_path":"36",
        "menu":1,
        "order":0,
        "name":"预收处理",
        "guard_name":"api",
        "path":"deposit",
        "path_name":"deposit",
        "title":"预收处理",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"finance.deposit",
        "pivot":{
            "role_id":1,
            "permission_id":40
        }
    },
    {
        "id":42,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"基础资料",
        "guard_name":"api",
        "path":"/infos",
        "path_name":"infos",
        "title":"基础资料",
        "icon":"ios-paper",
        "redirect":null,
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":42
        }
    },
    {
        "id":43,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":0,
        "name":"门店信息",
        "guard_name":"api",
        "path":"shop",
        "path_name":"shop",
        "title":"门店信息",
        "icon":"ios-home",
        "redirect":null,
        "component":"infos.shop",
        "pivot":{
            "role_id":1,
            "permission_id":43
        }
    },
    {
        "id":45,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":41,
        "name":"物料管理",
        "guard_name":"api",
        "path":"material-manager",
        "path_name":"material-manager",
        "title":"物料管理",
        "icon":"ios-pricetag",
        "redirect":null,
        "component":"infos.materialManager",
        "pivot":{
            "role_id":1,
            "permission_id":45
        }
    },
    {
        "id":46,
        "pid":86,
        "pid_path":"86",
        "menu":1,
        "order":0,
        "name":"维修项目",
        "guard_name":"api",
        "path":"project",
        "path_name":"project",
        "title":"维修项目",
        "icon":"folder",
        "redirect":null,
        "component":"infos.project",
        "pivot":{
            "role_id":1,
            "permission_id":46
        }
    },
    {
        "id":51,
        "pid":5,
        "pid_path":"1,5",
        "menu":0,
        "order":0,
        "name":"洗车-会员洗车",
        "guard_name":"api",
        "path":"tools-number",
        "path_name":"tools-number",
        "title":"会员洗车",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"tools.number",
        "pivot":{
            "role_id":1,
            "permission_id":51
        }
    },
    {
        "id":54,
        "pid":5,
        "pid_path":"1,5",
        "menu":0,
        "order":0,
        "name":"洗车-修改",
        "guard_name":"api",
        "path":"",
        "path_name":"",
        "title":"修改",
        "icon":"",
        "redirect":"",
        "component":"",
        "pivot":{
            "role_id":1,
            "permission_id":54
        }
    },
    {
        "id":55,
        "pid":5,
        "pid_path":"1,5",
        "menu":0,
        "order":0,
        "name":"洗车-完工",
        "guard_name":"api",
        "path":"",
        "path_name":"",
        "title":"完工",
        "icon":"",
        "redirect":"",
        "component":"",
        "pivot":{
            "role_id":1,
            "permission_id":55
        }
    },
    {
        "id":56,
        "pid":1,
        "pid_path":"1",
        "menu":0,
        "order":0,
        "name":"工单详情",
        "guard_name":"api",
        "path":"workorder-detail",
        "path_name":"workorder-detail",
        "title":"工单详情",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"tools.workorderDetail",
        "pivot":{
            "role_id":1,
            "permission_id":56
        }
    },
    {
        "id":57,
        "pid":1,
        "pid_path":"1",
        "menu":0,
        "order":0,
        "name":"新建预约单",
        "guard_name":"api",
        "path":"appointment",
        "path_name":"appointment",
        "title":"新建预约单",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"tools.appointment",
        "pivot":{
            "role_id":1,
            "permission_id":57
        }
    },
    {
        "id":58,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":0,
        "name":"员工管理",
        "guard_name":"api",
        "path":"employee",
        "path_name":"employee",
        "title":"员工管理",
        "icon":"ios-people-outline",
        "redirect":null,
        "component":"infos.employee",
        "pivot":{
            "role_id":1,
            "permission_id":58
        }
    },
    {
        "id":59,
        "pid":86,
        "pid_path":"86",
        "menu":1,
        "order":0,
        "name":"菜单设置",
        "guard_name":"api",
        "path":"permission",
        "path_name":"permission",
        "title":"菜单设置",
        "icon":"eye-disabled",
        "redirect":null,
        "component":"setting.permission",
        "pivot":{
            "role_id":1,
            "permission_id":59
        }
    },
    {
        "id":63,
        "pid":1,
        "pid_path":"1",
        "menu":0,
        "order":0,
        "name":"添加员工",
        "guard_name":"api",
        "path":"employee-add",
        "path_name":"employee-add",
        "title":"添加员工",
        "icon":"person-add",
        "redirect":null,
        "component":"infos.employeeAdd",
        "pivot":{
            "role_id":1,
            "permission_id":63
        }
    },
    {
        "id":64,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":6,
        "name":"角色管理",
        "guard_name":"api",
        "path":"role",
        "path_name":"role",
        "title":"角色管理",
        "icon":"ios-people-outline",
        "redirect":null,
        "component":"infos.role",
        "pivot":{
            "role_id":1,
            "permission_id":64
        }
    },
    {
        "id":66,
        "pid":86,
        "pid_path":"86",
        "menu":1,
        "order":6,
        "name":"字典管理",
        "guard_name":"api",
        "path":"dictionary",
        "path_name":"dictionary",
        "title":"字典管理",
        "icon":"ios-book",
        "redirect":null,
        "component":"infos.dictionary",
        "pivot":{
            "role_id":1,
            "permission_id":66
        }
    },
    {
        "id":72,
        "pid":86,
        "pid_path":"86",
        "menu":1,
        "order":6,
        "name":"城市管理",
        "guard_name":"api",
        "path":"city",
        "path_name":"city",
        "title":"城市管理",
        "icon":"location",
        "redirect":null,
        "component":"infos.city",
        "pivot":{
            "role_id":1,
            "permission_id":72
        }
    },
    {
        "id":73,
        "pid":9,
        "pid_path":"9",
        "menu":1,
        "order":4,
        "name":"供货商管理",
        "guard_name":"api",
        "path":"supplier",
        "path_name":"supplier",
        "title":"供货商管理",
        "icon":"cube",
        "redirect":null,
        "component":"purchase.supplier",
        "pivot":{
            "role_id":1,
            "permission_id":73
        }
    },
    {
        "id":74,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":42,
        "name":"物料分类",
        "guard_name":"api",
        "path":"materials",
        "path_name":"materials",
        "title":"物料分类",
        "icon":"pricetag",
        "redirect":null,
        "component":"infos.materials",
        "pivot":{
            "role_id":1,
            "permission_id":74
        }
    },
    {
        "id":75,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":43,
        "name":"物料品牌",
        "guard_name":"api",
        "path":"materials-brand",
        "path_name":"materials-brand",
        "title":"物料品牌",
        "icon":"pricetags",
        "redirect":null,
        "component":"infos.materialsBrand",
        "pivot":{
            "role_id":1,
            "permission_id":75
        }
    },
    {
        "id":76,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":7,
        "name":"顾客管理",
        "guard_name":"api",
        "path":"customer",
        "path_name":"customer",
        "title":"顾客管理",
        "icon":"person-stalker",
        "redirect":null,
        "component":"infos.customer",
        "pivot":{
            "role_id":1,
            "permission_id":76
        }
    },
    {
        "id":77,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":8,
        "name":"顾客车辆",
        "guard_name":"api",
        "path":"customer-car",
        "path_name":"customer-car",
        "title":"顾客车辆",
        "icon":"model-s",
        "redirect":null,
        "component":"infos.customerCar",
        "pivot":{
            "role_id":1,
            "permission_id":77
        }
    },
    {
        "id":78,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":19,
        "name":"项目物料",
        "guard_name":"api",
        "path":"project-material",
        "path_name":"project-material",
        "title":"项目物料",
        "icon":"folder",
        "redirect":null,
        "component":"infos.projectMaterial",
        "pivot":{
            "role_id":1,
            "permission_id":78
        }
    },
    {
        "id":79,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":20,
        "name":"车辆位置",
        "guard_name":"api",
        "path":"car-location",
        "path_name":"car-location",
        "title":"车辆位置",
        "icon":"android-car",
        "redirect":null,
        "component":"infos.carLocation",
        "pivot":{
            "role_id":1,
            "permission_id":79
        }
    },
    {
        "id":80,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":20,
        "name":"库房管理",
        "guard_name":"api",
        "path":"warehouse",
        "path_name":"warehouse",
        "title":"库房管理",
        "icon":"android-apps",
        "redirect":null,
        "component":"inventory.warehouse",
        "pivot":{
            "role_id":1,
            "permission_id":80
        }
    },
    {
        "id":81,
        "pid":0,
        "pid_path":"",
        "menu":0,
        "order":20,
        "name":"其它页面",
        "guard_name":"api",
        "path":"other",
        "path_name":"other",
        "title":"其它页面",
        "icon":"android-home",
        "redirect":"/home",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":81
        }
    },
    {
        "id":82,
        "pid":81,
        "pid_path":"81",
        "menu":0,
        "order":20,
        "name":"修改密码",
        "guard_name":"api",
        "path":"edit-password",
        "path_name":"edit-password",
        "title":"修改密码",
        "icon":"ios-eye",
        "redirect":null,
        "component":"other.editPassword",
        "pivot":{
            "role_id":1,
            "permission_id":82
        }
    },
    {
        "id":83,
        "pid":43,
        "pid_path":"42,43",
        "menu":0,
        "order":1,
        "name":"门店编辑",
        "guard_name":"api",
        "path":"shop-edit",
        "path_name":"shop-edit",
        "title":"门店编辑",
        "icon":"ios-home-outline",
        "redirect":"",
        "component":"infos.shopEdit",
        "pivot":{
            "role_id":1,
            "permission_id":83
        }
    },
    {
        "id":84,
        "pid":81,
        "pid_path":"",
        "menu":0,
        "order":0,
        "name":"表单页面",
        "guard_name":"api",
        "path":"form",
        "path_name":"form",
        "title":"表单页面",
        "icon":"grid",
        "redirect":"",
        "component":"other.form",
        "pivot":{
            "role_id":1,
            "permission_id":84
        }
    },
    {
        "id":85,
        "pid":1,
        "pid_path":"",
        "menu":0,
        "order":2,
        "name":"修改预约单",
        "guard_name":"api",
        "path":"appointment-edit",
        "path_name":"appointment-edit",
        "title":"修改预约单",
        "icon":"edit",
        "redirect":"",
        "component":"tools.appointmentEdit",
        "pivot":{
            "role_id":1,
            "permission_id":85
        }
    },
    {
        "id":86,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":9,
        "name":"系统设置",
        "guard_name":"api",
        "path":"/setting",
        "path_name":"setting",
        "title":"系统设置",
        "icon":"gear-b",
        "redirect":"permission",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":86
        }
    },
    {
        "id":87,
        "pid":9,
        "pid_path":"",
        "menu":1,
        "order":2,
        "name":"采购入库",
        "guard_name":"api",
        "path":"purchase-entry",
        "path_name":"purchase-entry",
        "title":"采购入库",
        "icon":"levels",
        "redirect":null,
        "component":"purchase.entry",
        "pivot":{
            "role_id":1,
            "permission_id":87
        }
    },
    {
        "id":91,
        "pid":9,
        "pid_path":"",
        "menu":1,
        "order":1,
        "name":"采购出库",
        "guard_name":"api",
        "path":"purchase-rollback",
        "path_name":"purchase-rollback",
        "title":"采购出库",
        "icon":"shuffle",
        "redirect":null,
        "component":"purchase.rollback",
        "pivot":{
            "role_id":1,
            "permission_id":91
        }
    },
    {
        "id":92,
        "pid":13,
        "pid_path":"",
        "menu":1,
        "order":13,
        "name":"库存查看",
        "guard_name":"api",
        "path":"inventory-stocks",
        "path_name":"inventory-stocks",
        "title":"库存查看",
        "icon":"information-circled",
        "redirect":null,
        "component":"inventory.stocks",
        "pivot":{
            "role_id":1,
            "permission_id":92
        }
    },
    {
        "id":93,
        "pid":10,
        "pid_path":"",
        "menu":0,
        "order":2,
        "name":"采购单明细",
        "guard_name":"api",
        "path":"purchase-detail",
        "path_name":"purchase-detail",
        "title":"采购单明细",
        "icon":"document-text",
        "redirect":null,
        "component":"purchase.detail",
        "pivot":{
            "role_id":1,
            "permission_id":93
        }
    }
]