const menu = [
    {
        "id":1,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"工单管理",
        "guard_name":"api",
        "path":"/tools",
        "path_name":"tools",
        "title":"工单",
        "icon":"wrench",
        "redirect":"",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":1
        }
    },
    {
        "id":2,
        "pid":1,
        "pid_path":"1",
        "menu":1,
        "order":0,
        "name":"预约",
        "guard_name":"api",
        "path":"touch",
        "path_name":"touch",
        "title":"预约",
        "icon":"chatbox-working",
        "redirect":"",
        "component":"tools.touch",
        "pivot":{
            "role_id":1,
            "permission_id":2
        }
    },
    {
        "id":3,
        "pid":1,
        "pid_path":"1",
        "menu":1,
        "order":0,
        "name":"新建接车单",
        "guard_name":"api",
        "path":"new-carflow",
        "path_name":"new-carflow",
        "title":"新建接车单",
        "icon":"model-s",
        "redirect":"",
        "component":"tools.newCarflow",
        "pivot":{
            "role_id":1,
            "permission_id":3
        }
    },
    {
        "id":4,
        "pid":1,
        "pid_path":"1",
        "menu":1,
        "order":0,
        "name":"工单",
        "guard_name":"api",
        "path":"workorder",
        "path_name":"workorder",
        "title":"工单",
        "icon":"ios-paper",
        "redirect":"",
        "component":"tools.workorder",
        "pivot":{
            "role_id":1,
            "permission_id":4
        }
    },
    {
        "id":5,
        "pid":1,
        "pid_path":"1",
        "menu":1,
        "order":0,
        "name":"洗车",
        "guard_name":"api",
        "path":"wash",
        "path_name":"wash",
        "title":"洗车",
        "icon":"ios-paper",
        "redirect":"",
        "component":"tools.wash",
        "pivot":{
            "role_id":1,
            "permission_id":5
        }
    },
    {
        "id":6,
        "pid":1,
        "pid_path":"1",
        "menu":1,
        "order":0,
        "name":"理赔",
        "guard_name":"api",
        "path":"claim",
        "path_name":"claim",
        "title":"理赔",
        "icon":"ios-paper",
        "redirect":"",
        "component":"tools.claim",
        "pivot":{
            "role_id":1,
            "permission_id":6
        }
    },
    {
        "id":7,
        "pid":1,
        "pid_path":"1",
        "menu":1,
        "order":0,
        "name":"销售",
        "guard_name":"api",
        "path":"sell",
        "path_name":"sell",
        "title":"销售",
        "icon":"ios-paper",
        "redirect":"",
        "component":"tools.sell",
        "pivot":{
            "role_id":1,
            "permission_id":7
        }
    },
    {
        "id":8,
        "pid":1,
        "pid_path":"1",
        "menu":1,
        "order":0,
        "name":"附表",
        "guard_name":"api",
        "path":"attached",
        "path_name":"attached",
        "title":"附表",
        "icon":"ios-paper",
        "redirect":"",
        "component":"tools.attached",
        "pivot":{
            "role_id":1,
            "permission_id":8
        }
    },
    {
        "id":9,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"采购管理",
        "guard_name":"api",
        "path":"/purchase",
        "path_name":"purchase",
        "title":"采购",
        "icon":"ios-cart",
        "redirect":"",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":9
        }
    },
    {
        "id":10,
        "pid":9,
        "pid_path":"9",
        "menu":1,
        "order":0,
        "name":"采购订单",
        "guard_name":"api",
        "path":"order",
        "path_name":"order",
        "title":"采购订单",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"purchase.order",
        "pivot":{
            "role_id":1,
            "permission_id":10
        }
    },
    {
        "id":11,
        "pid":9,
        "pid_path":"9",
        "menu":1,
        "order":0,
        "name":"采购退货",
        "guard_name":"api",
        "path":"rollback",
        "path_name":"rollback",
        "title":"采购退货",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"purchase.rollback",
        "pivot":{
            "role_id":1,
            "permission_id":11
        }
    },
    {
        "id":12,
        "pid":9,
        "pid_path":"9",
        "menu":1,
        "order":0,
        "name":"采购平台",
        "guard_name":"api",
        "path":"platform",
        "path_name":"platform",
        "title":"采购平台",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"purchase.platform",
        "pivot":{
            "role_id":1,
            "permission_id":12
        }
    },
    {
        "id":13,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"库存管理",
        "guard_name":"api",
        "path":"/inventory",
        "path_name":"inventory",
        "title":"库存",
        "icon":"ios-albums",
        "redirect":"",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":13
        }
    },
    {
        "id":14,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":0,
        "name":"工单出入库",
        "guard_name":"api",
        "path":"warehouse",
        "path_name":"warehouse",
        "title":"工单出入库",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"inventory.warehouse",
        "pivot":{
            "role_id":1,
            "permission_id":14
        }
    },
    {
        "id":15,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":0,
        "name":"入库单",
        "guard_name":"api",
        "path":"entry",
        "path_name":"entry",
        "title":"入库单",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"inventory.entry",
        "pivot":{
            "role_id":1,
            "permission_id":15
        }
    },
    {
        "id":16,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":0,
        "name":"出库单",
        "guard_name":"api",
        "path":"outbound",
        "path_name":"outbound",
        "title":"出库单",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"inventory.outbound",
        "pivot":{
            "role_id":1,
            "permission_id":16
        }
    },
    {
        "id":17,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":0,
        "name":"盘点",
        "guard_name":"api",
        "path":"check",
        "path_name":"check",
        "title":"盘点",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"inventory.check",
        "pivot":{
            "role_id":1,
            "permission_id":17
        }
    },
    {
        "id":18,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":0,
        "name":"调价",
        "guard_name":"api",
        "path":"revise",
        "path_name":"revise",
        "title":"调价",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"inventory.revise",
        "pivot":{
            "role_id":1,
            "permission_id":18
        }
    },
    {
        "id":19,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":0,
        "name":"货位调整",
        "guard_name":"api",
        "path":"adjustment",
        "path_name":"adjustment",
        "title":"货位调整",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"inventory.adjustment",
        "pivot":{
            "role_id":1,
            "permission_id":19
        }
    },
    {
        "id":20,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":0,
        "name":"跨店调拨",
        "guard_name":"api",
        "path":"allocation",
        "path_name":"allocation",
        "title":"跨店调拨",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"inventory.allocation",
        "pivot":{
            "role_id":1,
            "permission_id":20
        }
    },
    {
        "id":21,
        "pid":13,
        "pid_path":"13",
        "menu":1,
        "order":0,
        "name":"库存台账",
        "guard_name":"api",
        "path":"journal",
        "path_name":"journal",
        "title":"库存台账",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"inventory.journal",
        "pivot":{
            "role_id":1,
            "permission_id":21
        }
    },
    {
        "id":22,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"营销管理",
        "guard_name":"api",
        "path":"/market",
        "path_name":"market",
        "title":"营销",
        "icon":"trophy",
        "redirect":"",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":22
        }
    },
    {
        "id":23,
        "pid":22,
        "pid_path":"22",
        "menu":1,
        "order":0,
        "name":"会员卡",
        "guard_name":"api",
        "path":"club",
        "path_name":"club",
        "title":"会员卡",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"market.club",
        "pivot":{
            "role_id":1,
            "permission_id":23
        }
    },
    {
        "id":24,
        "pid":22,
        "pid_path":"22",
        "menu":1,
        "order":0,
        "name":"微信客户",
        "guard_name":"api",
        "path":"customer",
        "path_name":"customer",
        "title":"微信客户",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"market.customer",
        "pivot":{
            "role_id":1,
            "permission_id":24
        }
    },
    {
        "id":25,
        "pid":22,
        "pid_path":"22",
        "menu":1,
        "order":0,
        "name":"营销套餐设置",
        "guard_name":"api",
        "path":"combo",
        "path_name":"combo",
        "title":"套餐设置",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"market.combo",
        "pivot":{
            "role_id":1,
            "permission_id":25
        }
    },
    {
        "id":26,
        "pid":22,
        "pid_path":"22",
        "menu":1,
        "order":0,
        "name":"设置",
        "guard_name":"api",
        "path":"setting",
        "path_name":"setting",
        "title":"设置",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"market.setting",
        "pivot":{
            "role_id":1,
            "permission_id":26
        }
    },
    {
        "id":27,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"数据管理",
        "guard_name":"api",
        "path":"/data",
        "path_name":"data",
        "title":"数据管理",
        "icon":"shuffle",
        "redirect":"",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":27
        }
    },
    {
        "id":28,
        "pid":27,
        "pid_path":"27",
        "menu":1,
        "order":0,
        "name":"车型信息",
        "guard_name":"api",
        "path":"cartype",
        "path_name":"cartype",
        "title":"车型信息",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"dataManager.cartype",
        "pivot":{
            "role_id":1,
            "permission_id":28
        }
    },
    {
        "id":29,
        "pid":27,
        "pid_path":"27",
        "menu":1,
        "order":0,
        "name":"配件信息",
        "guard_name":"api",
        "path":"autoparts",
        "path_name":"autoparts",
        "title":"配件信息",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"dataManager.autoparts",
        "pivot":{
            "role_id":1,
            "permission_id":29
        }
    },
    {
        "id":30,
        "pid":27,
        "pid_path":"27",
        "menu":1,
        "order":0,
        "name":"保养信息",
        "guard_name":"api",
        "path":"careinfo",
        "path_name":"careinfo",
        "title":"保养信息",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"dataManager.careinfo",
        "pivot":{
            "role_id":1,
            "permission_id":30
        }
    },
    {
        "id":31,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"报表管理",
        "guard_name":"api",
        "path":"/chart",
        "path_name":"chart",
        "title":"报表管理",
        "icon":"pie-graph",
        "redirect":"",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":31
        }
    },
    {
        "id":32,
        "pid":31,
        "pid_path":"31",
        "menu":1,
        "order":0,
        "name":"财务报表",
        "guard_name":"api",
        "path":"chart-financial",
        "path_name":"chart-financial",
        "title":"财务报表",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"chart.chartFinancial",
        "pivot":{
            "role_id":1,
            "permission_id":32
        }
    },
    {
        "id":33,
        "pid":31,
        "pid_path":"31",
        "menu":1,
        "order":0,
        "name":"营业报表",
        "guard_name":"api",
        "path":"chart-operating",
        "path_name":"chart-operating",
        "title":"营业报表",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"chart.chartOperating",
        "pivot":{
            "role_id":1,
            "permission_id":33
        }
    },
    {
        "id":34,
        "pid":31,
        "pid_path":"31",
        "menu":1,
        "order":0,
        "name":"采购报表",
        "guard_name":"api",
        "path":"chart-purchase",
        "path_name":"chart-purchase",
        "title":"采购报表",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"chart.chartPurchase",
        "pivot":{
            "role_id":1,
            "permission_id":34
        }
    },
    {
        "id":35,
        "pid":31,
        "pid_path":"31",
        "menu":1,
        "order":0,
        "name":"客户报表",
        "guard_name":"api",
        "path":"chart-customer",
        "path_name":"chart-customer",
        "title":"客户报表",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"chart.chartCustomer",
        "pivot":{
            "role_id":1,
            "permission_id":35
        }
    },
    {
        "id":36,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"财务管理",
        "guard_name":"api",
        "path":"/finance",
        "path_name":"finance",
        "title":"财务管理",
        "icon":"social-yen",
        "redirect":"",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":36
        }
    },
    {
        "id":37,
        "pid":36,
        "pid_path":"36",
        "menu":1,
        "order":0,
        "name":"应收",
        "guard_name":"api",
        "path":"account",
        "path_name":"account",
        "title":"应收",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"finance.account",
        "pivot":{
            "role_id":1,
            "permission_id":37
        }
    },
    {
        "id":38,
        "pid":36,
        "pid_path":"36",
        "menu":1,
        "order":0,
        "name":"应收账款",
        "guard_name":"api",
        "path":"receivable",
        "path_name":"receivable",
        "title":"应收账款",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"finance.receivable",
        "pivot":{
            "role_id":1,
            "permission_id":38
        }
    },
    {
        "id":39,
        "pid":36,
        "pid_path":"36",
        "menu":1,
        "order":0,
        "name":"应付",
        "guard_name":"api",
        "path":"payable",
        "path_name":"payable",
        "title":"应付",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"finance.payable",
        "pivot":{
            "role_id":1,
            "permission_id":39
        }
    },
    {
        "id":40,
        "pid":36,
        "pid_path":"36",
        "menu":1,
        "order":0,
        "name":"预收处理",
        "guard_name":"api",
        "path":"deposit",
        "path_name":"deposit",
        "title":"预收处理",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"finance.deposit",
        "pivot":{
            "role_id":1,
            "permission_id":40
        }
    },
    {
        "id":41,
        "pid":36,
        "pid_path":"36",
        "menu":1,
        "order":0,
        "name":"其它收支",
        "guard_name":"api",
        "path":"otherfund",
        "path_name":"otherfund",
        "title":"其它收支",
        "icon":"ios-list-outline",
        "redirect":"",
        "component":"finance.otherfund",
        "pivot":{
            "role_id":1,
            "permission_id":41
        }
    },
    {
        "id":42,
        "pid":0,
        "pid_path":"",
        "menu":1,
        "order":0,
        "name":"基础资料管理",
        "guard_name":"api",
        "path":"/infos",
        "path_name":"infos",
        "title":"基础资料",
        "icon":"person",
        "redirect":"",
        "component":"Mainbody",
        "pivot":{
            "role_id":1,
            "permission_id":42
        }
    },
    {
        "id":43,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":0,
        "name":"基础资料",
        "guard_name":"api",
        "path":"info-msg",
        "path_name":"info-msg",
        "title":"基础资料",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"infos.infoMsg",
        "pivot":{
            "role_id":1,
            "permission_id":43
        }
    },
    {
        "id":44,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":0,
        "name":"客户车辆",
        "guard_name":"api",
        "path":"info-customer",
        "path_name":"info-customer",
        "title":"客户车辆",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"infos.infoCustomer",
        "pivot":{
            "role_id":1,
            "permission_id":44
        }
    },
    {
        "id":45,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":0,
        "name":"材料信息",
        "guard_name":"api",
        "path":"info-material",
        "path_name":"info-material",
        "title":"材料信息",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"infos.infoMaterial",
        "pivot":{
            "role_id":1,
            "permission_id":45
        }
    },
    {
        "id":46,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":0,
        "name":"项目信息",
        "guard_name":"api",
        "path":"info-project",
        "path_name":"info-project",
        "title":"项目信息",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"infos.infoProject",
        "pivot":{
            "role_id":1,
            "permission_id":46
        }
    },
    {
        "id":47,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":0,
        "name":"供应商信息",
        "guard_name":"api",
        "path":"info-supplier",
        "path_name":"info-supplier",
        "title":"供应商信息",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"infos.infoSupplier",
        "pivot":{
            "role_id":1,
            "permission_id":47
        }
    },
    {
        "id":48,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":0,
        "name":"保险公司",
        "guard_name":"api",
        "path":"info-insurer",
        "path_name":"info-insurer",
        "title":"保险公司",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"infos.infoInsurer",
        "pivot":{
            "role_id":1,
            "permission_id":48
        }
    },
    {
        "id":49,
        "pid":42,
        "pid_path":"42",
        "menu":1,
        "order":0,
        "name":"基础资料套餐设置",
        "guard_name":"api",
        "path":"info-package",
        "path_name":"info-package",
        "title":"套餐设置",
        "icon":"ios-paper-outline",
        "redirect":"",
        "component":"infos.infoPackage",
        "pivot":{
            "role_id":1,
            "permission_id":49
        }
    },
    {
        "id":50,
        "pid":5,
        "pid_path":"1,5",
        "menu":0,
        "order":0,
        "name":"洗车-现金洗车",
        "guard_name":"api",
        "path":"",
        "path_name":"",
        "title":"",
        "icon":"",
        "redirect":"",
        "component":"",
        "pivot":{
            "role_id":1,
            "permission_id":50
        }
    },
    {
        "id":51,
        "pid":5,
        "pid_path":"1,5",
        "menu":0,
        "order":0,
        "name":"洗车-会员洗车",
        "guard_name":"api",
        "path":"",
        "path_name":"",
        "title":"",
        "icon":"",
        "redirect":"",
        "component":"",
        "pivot":{
            "role_id":1,
            "permission_id":51
        }
    },
    {
        "id":52,
        "pid":5,
        "pid_path":"1,5",
        "menu":0,
        "order":0,
        "name":"洗车-结算",
        "guard_name":"api",
        "path":"",
        "path_name":"",
        "title":"",
        "icon":"",
        "redirect":"",
        "component":"",
        "pivot":{
            "role_id":1,
            "permission_id":52
        }
    },
    {
        "id":53,
        "pid":5,
        "pid_path":"1,5",
        "menu":0,
        "order":0,
        "name":"洗车-收款",
        "guard_name":"api",
        "path":"",
        "path_name":"",
        "title":"",
        "icon":"",
        "redirect":"",
        "component":"",
        "pivot":{
            "role_id":1,
            "permission_id":53
        }
    },
    {
        "id":54,
        "pid":5,
        "pid_path":"1,5",
        "menu":0,
        "order":0,
        "name":"洗车-修改",
        "guard_name":"api",
        "path":"",
        "path_name":"",
        "title":"",
        "icon":"",
        "redirect":"",
        "component":"",
        "pivot":{
            "role_id":1,
            "permission_id":54
        }
    },
    {
        "id":55,
        "pid":5,
        "pid_path":"1,5",
        "menu":0,
        "order":0,
        "name":"洗车-完工",
        "guard_name":"web",
        "path":"",
        "path_name":"",
        "title":"",
        "icon":"",
        "redirect":"",
        "component":"",
        "pivot":{
            "role_id":1,
            "permission_id":55
        }
    }
]